from enum import Enum
from typing import List

class EgyptianSymbol(str, Enum):
    # Ankh = "Ankh"
    EyeOfHorus = "EyeOfHorus"
    # WingedScarab = "WingedScarab"
    HorusFalcon = "HorusFalcon"
    HieroglyphTablet = "HieroglyphTablet"
    # Pyramid = "Pyramid"
    Sphinx = "Sphinx"
    # PharaohFront = "PharaohFront"
    # AnubisSeated = "AnubisSeated"
    # AnubisStanding = "AnubisStanding"
    # CrookAndFlail = "CrookAndFlail"
    BlueLotus = "BlueLotus"
    # PapyrusFlowers = "PapyrusFlowers"
    # WingedScarabBlue = "WingedScarabBlue"
    Cobra = "Cobra"
    # PharaohSeated = "PharaohSeated"
    # HieroglyphBirdTablet = "HieroglyphBirdTablet"
    # AncientScroll = "AncientScroll"
    # EyeOfHorusGold = "EyeOfHorusGold"
    GoldenFeather = "GoldenFeather"
    HieroglyphVase = "HieroglyphVase"
    # ScarabPendant = "ScarabPendant"
    # ScalesOfJustice = "ScalesOfJustice"
    Hourglass = "Hourglass"
    # EgyptianTemple = "EgyptianTemple"
    EgyptianChest = "EgyptianChest"
    # SealedScroll = "SealedScroll"
    SunDisk = "SunDisk"
    # HieroglyphStone = "HieroglyphStone"
    # FlyingFalcon = "FlyingFalcon"
    # AnubisWalking = "AnubisWalking"
    # PharaohProfile = "PharaohProfile"
    # ScarabRed = "ScarabRed"
    # CrookAndFlailBlue = "CrookAndFlailBlue"
    PalmTree = "PalmTree"
    # TempleDoorway = "TempleDoorway"
    EgyptianBoat = "EgyptianBoat"
    # SacredBrazier = "SacredBrazier"
    # AnubisStatue = "AnubisStatue"
    # SunCompass = "SunCompass"

    @classmethod
    def list_all(cls) -> List[str]:
        """Returns a list of all symbol string values."""
        return [symbol.value for symbol in cls]
